import Foundation

extension SpaceStory {
    static let bank: [SpaceStory] = [
        .init(id: "moon-craters", category: .moon, title: "The Crater Detective", pages: [
            .init(art: "Rocket", text: "Ready, little explorer? Our pretend rocket is visiting the Moon. Three, two, one, lift off!", action: "Fly to the Moon"),
            .init(art: "Moon", text: "Hello, Moon! Those round dents are called craters. Let's look for a big one and a little one.", action: "Explore a crater"),
            .init(art: "Moon", text: "Long ago, space rocks bumped into the Moon and made many craters. Make a little circle with your finger.", action: "Try a Moon step"),
            .init(art: "Moon", text: "The Moon pulls us down less strongly than Earth does. Astronauts can take bouncy steps there. Wiggle your fingers like tiny feet!", action: "Look for home"),
            .init(art: "Earth", text: "There's Earth, our home! The Moon travels around Earth. Let's wave to our blue planet.", action: "Bring our discovery home"),
            .init(art: "Moon", text: "Mission complete! We discovered craters and practiced pretend Moon steps. You are a wonderful crater detective!", action: ""),
        ]),
        .init(id: "moon-shine", category: .moon, title: "The Moonlight Mystery", pages: [
            .init(art: "Rocket", text: "Our pretend rocket has a mystery to solve. How does the Moon look bright? Let's investigate together!", action: "Visit our neighbor"),
            .init(art: "Moon", text: "The Moon is Earth's space neighbor. Sometimes we can see it in the daytime, too. Hello, neighbor!", action: "Find the light"),
            .init(art: "Sun", text: "The Sun makes its own light. Some sunlight reaches the Moon. We'll explore with pictures and never look straight at the real Sun.", action: "Follow the moonlight"),
            .init(art: "Moon", text: "Sunlight bounces off the Moon toward us. The Moon does not make its own light. Mystery solved!", action: "Wave to Earth"),
            .init(art: "Earth", text: "From Earth, the bright part of the Moon can look different on different nights. The Moon itself stays round.", action: "Celebrate our discovery"),
            .init(art: "Moon", text: "You solved the moonlight mystery! When you're outside with a grown-up, see if you can spot the Moon.", action: ""),
        ]),
        .init(id: "earth-blue", category: .earth, title: "The Blue Planet Picnic", pages: [
            .init(art: "Rocket", text: "Pack an imaginary picnic! Our pretend rocket will peek at Earth from space, then bring us home.", action: "Look at Earth"),
            .init(art: "Earth", text: "Look at all that blue! Oceans cover much of Earth. Can you point to a blue part of our picture?", action: "Find the land"),
            .init(art: "Earth", text: "Earth has land, too. People, plants, and many animals live on land. Pretend to wave to a tiny tree below.", action: "Watch the clouds"),
            .init(art: "Earth", text: "Those fluffy white shapes remind us of clouds. Earth has air around it. Take a gentle breath with me.", action: "Head home for a picnic"),
            .init(art: "Rocket", text: "Our pretend rocket is coming home. On Earth we have water to drink and air to breathe. What a special home!", action: "Unpack our picnic"),
            .init(art: "Earth", text: "Picnic time! We found oceans, land, and clouds. Let's care for our home planet together.", action: ""),
        ]),
        .init(id: "earth-day", category: .earth, title: "The Day and Night Delivery", pages: [
            .init(art: "Rocket", text: "We have a pretend delivery for Earth: a good-morning wave and a good-night wave. Let's find where they belong!", action: "Find the sunshine"),
            .init(art: "Sun", text: "The Sun lights one side of Earth at a time. That side has daytime. Say, good morning!", action: "Watch Earth turn"),
            .init(art: "Earth", text: "Earth slowly spins. Imagine turning a ball in your hands. A place on Earth turns toward the sunlight, then away.", action: "Find the night side"),
            .init(art: "Earth", text: "When our part of Earth faces away from the Sun, it is nighttime. Give a little good-night wave.", action: "Return to our neighborhood"),
            .init(art: "Rocket", text: "Our pretend delivery is done! Earth keeps turning while we play and while we sleep.", action: "Remember our discovery"),
            .init(art: "Earth", text: "Day and night happen as Earth spins. We delivered both waves. Good exploring, little space friend!", action: ""),
        ]),
        .init(id: "mars-rover", category: .mars, title: "The Red Planet Rover", pages: [
            .init(art: "Rocket", text: "Beep, beep! Our pretend rocket is taking a robot explorer to Mars. Can you make a little robot beep?", action: "Find the red planet"),
            .init(art: "Mars", text: "There's Mars! Rusty minerals in its dusty ground make it look reddish. Point to our red planet picture.", action: "Meet our pretend rover"),
            .init(art: "Mars", text: "A rover is a robot that drives and explores. Real rovers help scientists study Mars. Roll your hands like little wheels.", action: "Explore the rocky ground"),
            .init(art: "Mars", text: "Mars has rocks, hills, and dusty ground. Our pretend rover stops to look carefully. Scientists learn by noticing things.", action: "Send a message home"),
            .init(art: "Earth", text: "Beep! Our pretend rover sends a message to Earth. We found a rocky, reddish world!", action: "Cheer for our rover"),
            .init(art: "Mars", text: "Great exploring! Mars is a planet, and rovers are robot explorers. Give our pretend rover a happy beep!", action: ""),
        ]),
        .init(id: "mars-moons", category: .mars, title: "Two Little Mars Moons", pages: [
            .init(art: "Rocket", text: "Our pretend rocket is visiting Mars to find its two little moons. Let's count together on our trip!", action: "Meet Mars"),
            .init(art: "Mars", text: "Mars is smaller than Earth. Its dusty surface looks reddish. Hello, Mars! We're here to meet your moons.", action: "Look for one moon"),
            .init(art: "Mars", text: "Mars has a moon called Phobos. That's one moon. Hold up one finger if you like.", action: "Find the second moon"),
            .init(art: "Mars", text: "Its other moon is called Deimos. One, two! These moons are small and lumpy, not smooth round balls.", action: "Make two little moon shapes"),
            .init(art: "Mars", text: "Both little moons travel around Mars. Make two tiny shapes with your hands and move them around an imaginary planet.", action: "Finish our counting trip"),
            .init(art: "Earth", text: "Home again! Earth has one Moon, and Mars has two. We counted and explored together. Well done!", action: ""),
        ]),
        .init(id: "jupiter-stripes", category: .jupiter, title: "The Giant Stripe Search", pages: [
            .init(art: "Rocket", text: "Our pretend rocket is looking for a giant striped planet. Let's visit Jupiter and see what we notice!", action: "Meet the giant planet"),
            .init(art: "Jupiter", text: "Jupiter is the biggest planet in our solar system. Stretch your arms wide, or make a big circle with your hands.", action: "Look for stripes"),
            .init(art: "Jupiter", text: "Jupiter's colorful stripes are bands of clouds. Trace an imaginary stripe from one side to the other.", action: "Look from our spaceship"),
            .init(art: "Jupiter", text: "Jupiter has no solid ground to stand on like Earth. We'll explore from our pretend spaceship instead of landing.", action: "Remember the cloud bands"),
            .init(art: "Jupiter", text: "Light stripe, dark stripe! The clouds make wonderful patterns. What colors can you find in our picture?", action: "Send a picture home"),
            .init(art: "Earth", text: "Our pretend picture is home! Jupiter is a giant planet with cloud bands. You were a wonderful stripe spotter!", action: ""),
        ]),
        .init(id: "jupiter-storm", category: .jupiter, title: "The Swirling Storm Watch", pages: [
            .init(art: "Rocket", text: "Our pretend spaceship is going to watch Jupiter from far above its clouds. Let's be gentle storm watchers!", action: "Look at Jupiter"),
            .init(art: "Jupiter", text: "Jupiter has a huge storm called the Great Red Spot. Can you find the spot on our planet picture?", action: "Make a little swirl"),
            .init(art: "Jupiter", text: "The storm swirls around. Draw a slow circle in the air with one finger. Round and round!", action: "Stay above the clouds"),
            .init(art: "Jupiter", text: "Winds move Jupiter's clouds into bands. We stay in our pretend spaceship and watch from far away.", action: "Spot the giant again"),
            .init(art: "Jupiter", text: "Jupiter is bigger than every other planet in our solar system. What a big world for a big storm!", action: "Bring our story home"),
            .init(art: "Earth", text: "We watched a giant planet and learned about its swirling storm. Our pretend adventure is safely home. Hooray!", action: ""),
        ]),
        .init(id: "saturn-rings", category: .saturn, title: "The Ring Explorer", pages: [
            .init(art: "Rocket", text: "Our pretend rocket has a special mission: find the planet with the beautiful rings. Let's visit Saturn!", action: "Find Saturn"),
            .init(art: "Saturn", text: "Hello, Saturn! Its rings go around the planet. Make a wide ring with your arms or your fingers.", action: "Explore the rings"),
            .init(art: "Saturn", text: "The rings are made of many pieces of ice and rock. They are not one solid hoop. Imagine lots of tiny pieces together.", action: "Look without landing"),
            .init(art: "Saturn", text: "We cannot walk on Saturn's rings like a road. Our pretend rocket watches from a safe distance.", action: "Wave to the ringed planet"),
            .init(art: "Saturn", text: "Saturn is a giant planet without a solid surface like Earth's. We'll wave from our pretend spaceship.", action: "Bring our discovery home"),
            .init(art: "Earth", text: "Mission complete! Saturn's rings are made of ice and rock. You are a wonderful ring explorer!", action: ""),
        ]),
        .init(id: "saturn-postcard", category: .saturn, title: "A Postcard from Saturn", pages: [
            .init(art: "Rocket", text: "Let's make a pretend space postcard for a friend. Our picture will show Saturn and its lovely rings!", action: "Look at our subject"),
            .init(art: "Saturn", text: "Saturn is the second-biggest planet in our solar system. Jupiter is bigger. Our postcard needs room for a giant!", action: "Draw a ring in the air"),
            .init(art: "Saturn", text: "Its bright rings circle the planet. Trace a long, round shape in the air. What a lovely pretend drawing!", action: "Add tiny ring pieces"),
            .init(art: "Saturn", text: "The rings contain lots of ice and rock pieces. Wiggle your fingers like many little pieces traveling together.", action: "Write our pretend message"),
            .init(art: "Saturn", text: "Our message says: hello from Saturn! We explored from our spaceship because Saturn has no solid ground like Earth.", action: "Deliver our postcard"),
            .init(art: "Earth", text: "Our pretend postcard has arrived! Tell a grown-up one thing you noticed about Saturn. Thank you, space artist!", action: ""),
        ]),
        .init(id: "sun-star", category: .sun, title: "Meet Our Special Star", pages: [
            .init(art: "Rocket", text: "Today our pretend rocket stays far from the Sun. We will learn about it through pictures. Ready to meet our special star?", action: "Meet the Sun"),
            .init(art: "Sun", text: "The Sun is a star. It makes light and gives warmth to Earth. Our cheerful picture is pretending to smile!", action: "Think about sunlight"),
            .init(art: "Earth", text: "Sunlight helps plants grow on Earth. Pretend your hands are little leaves opening in the light.", action: "Visit with our picture"),
            .init(art: "Sun", text: "The real Sun is very hot. We never look straight at it. Our story picture is a safe way to explore together.", action: "Send a thank-you wave"),
            .init(art: "Earth", text: "Our planet travels around the Sun. Imagine moving a little Earth around a big star. Around we go!", action: "Celebrate our star"),
            .init(art: "Sun", text: "Thank you, Sun, for light and warmth! We learned that the Sun is a star. What a bright discovery!", action: ""),
        ]),
        .init(id: "sun-light", category: .sun, title: "The Sunlight Helper", pages: [
            .init(art: "Earth", text: "A pretend little seed is waiting on Earth. What helps it grow? Let's follow the story of sunlight together.", action: "Find our star"),
            .init(art: "Sun", text: "The Sun sends light toward Earth. It is our nearest star. We use our story picture instead of looking at the real Sun.", action: "Help our pretend seed"),
            .init(art: "Earth", text: "With water, air, and light, many plants can grow. Pretend your little seed is stretching into a leafy plant.", action: "Remember the light source"),
            .init(art: "Sun", text: "The Sun makes its own light. The Moon does not. Moonlight is sunlight that bounces off the Moon.", action: "Wave to the Moon"),
            .init(art: "Moon", text: "Hello, Moon! You reflect sunlight. Our pretend plant and our shining Moon both remind us of the Sun.", action: "Finish our sunlight story"),
            .init(art: "Earth", text: "Our little pretend plant has leaves! We learned about sunlight, our star, and reflected moonlight. Great discovering!", action: ""),
        ]),
    ]
}
